### PR TITLE
Move pm2 env vars

### PR DESCRIPTION
**Pull request by adaschevici**
1) Moved the env vars from ecosystem for pm2 so that they are taken from
.env instead with docker-compose. the ecosystem file still exists but it
uses process.env to get the vars
2) TBC: should we have separate env vars for the
CMS_ADMIN/CMS_DB/CMS_PASSWORD? It may make sense to merge these at some
point
3) TBC: should pm2 be used? should we rely on container orchestration
instead?

### CODE REVIEW

**Comment by adaschevici** [comment]
do not merge this yet

**Comment by MaximeRobeyns** [comment]
Hey Artur,

Would you be happy accessing secrets in the following way:
1. get the value of an environment variable with a `_FILE` suffix; e.g. for `CMS_PASSWORD`, you would look for `CMS_PASSWORD_FILE`
2. this environment variable contains the location of a file with the value in plain text; simply read the file to get the secret.

While it's admittedly slightly cumbersome to have to read files, it only takes a small wrapper function. 
Using this approach has the benefit that
- secrets are always handled securely; we can store them all as docker secrets
- we never write them in plain text in our images; the files pointed to by the environment variables are pseudo files which live in memory and are never written to disk

To actually set the variables in the first place, I've written a script this morning to take `key: value` pairs written in a (gpg encrypted) file on our workstations, and set them all as docker secrets. I'll explain this in more detail once the documentation is up!

**Comment by adaschevici** [comment]
so instead of using the `process.env.<VAR_NAME>` to read a file and load that var?

**Comment by MaximeRobeyns** [comment]
Yep that's right
Of course you can still use React's `process.env.development`, `process.env.production` etc for things like selecting database names, ports and other non-sensitive variables, but for things like passwords, you'd read the plain text file pointed to by the relevant environment variable. These would be stored somewhere like `/run/secrets/<VAR_NAME>`

**Pull request merged**
